### ISSUE TITLE
Error was disabled when compile with -mrelax

### ISSUE THREAD

**Issue by luxufan** [riscv-android-src/toolchain-llvm-project#3]
Upstreaming LLD didn't support linker relaxation for RISCV. When the linker find relocations that used by linker relaxation, it will report error and suggest us to compile with -mno-relax

In this repository, Instead of adding a -mno-relax option to compile flags, the code that reports error was deleted directly in LLD source code to avoid reporting error. I think adding -mno-relax option is a better solution. :)

**Comment by unicornx** [comment]
Add some more comments.

I would recommend keep the same as upstream LLD should be better and this help us catch the unsupported behavior. 

We here tried adding `-mno-relax` in `build/soong/cc/config/riscv64_device.go` as below and seems it works, but anyway this requires to roll-back the LLD the same as upstream version.

```
var (
	riscv64Cflags = []string{
		// Help catch common 32/64-bit errors.
                ......
		"-mno-relax",
	}
```

**Comment by unicornx** [comment]
I tried adding "-mno-relax" and it can pass build and run on emulator.

But I met another problem.
I see that RVI upstream build assembly .S files with "-fno-integrated-as". As I know aosp 12 has switched over to llvm/clang toolchain totally, so we'd better to use LLVM integrated assembler, but not GNU as, and I see for other ARCH, they all use LLVM integrated assembler. 

But when I tried remove "-fno-integrated-as", I can pass build but failed run system on emulator.
log: [emu.log](https://github.com/riscv-android-src/toolchain-llvm-project/files/8121393/emu.log)

So my question is, is there any problem in LLVM-as for RVI upstream?

**Comment by unicornx** [comment]
With latest github aosp, tried with "-mno-relax" plus integrated as, it works now.
Related PR's are:
- https://github.com/riscv-android-src/platform-build-soong/pull/4
- https://github.com/riscv-android-src/platform-build-soong/pull/5

Now only TODO left is to update the lld to revert the deleted code about reporting error.

**Comment by unicornx** [comment]
lld has been updated with https://github.com/riscv-android-src/toolchain-llvm-project/commit/e2cf2cfc15c6e7c40f7c5783d631b06aa3a7cd73, please close this issue.

**Comment by luxufan** [comment]
Fixed by https://github.com/riscv-android-src/toolchain-llvm-project/commit/e2cf2cfc15c6e7c40f7c5783d631b06aa3a7cd73
